### ISSUE TITLE
Question about the game translation

### ISSUE THREAD

**Issue by marius851000** [SanyaWaffles/ScootHardDX#2]
Hi. I wish to help translating the game in french (as I already did -- although not yet published) for sulphur nimbus : hel's elixir). On discord, on a my little pony related server, I talked to someone who told me he/she was already translating the game with google, I've asked him to ask you to add me in the list of people who can translate the game, but that is now about a week I've asked this, and I have not yet received any response, so I've decided to use another communication method.

Thank.

**Comment by SanyaWaffles** [comment]
What is your email for Google Docs? I'll add you to the spreadsheet.

**Comment by marius851000** [comment]
marius851000@gmail.com (at least it's the mail of my google account. I otherwise prefer mariusdavid@laposte.net , but is not linked to my google accound).

**Comment by SanyaWaffles** [comment]
you should be added now. Sorry about the slow response, been dealing with some personal stuff.
